spring:
  thymeleaf:
    cache: false
    prefix: "classpath:/templates/"
    suffix: ".html"
    enabled: true
    encoding: UTF-8
    mode: "HTML"
    check-template-location: true
    template-resolver-order: 1
#    view-names:
#    excluded-view-names:
