spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springfox:
  documentation:
    open-api:
      enabled: true
    enabled: true
    swagger-ui:
      enabled: true
      base-url: ""